### ISSUE TITLE
Add offline push notification

### ISSUE THREAD

**Issue by Fale** [lgallard/qBittorrent-Client#27]
Please, do create a way so if you are mentioned and you have no clients connected to the server, your phone (and/or other android device) receives a push notification, so you can open the app and read/reply, without killing your phone keeping the app open all day long

**Comment by lgallard** [comment]
HI Fale,

Version 3.7.1 added notification for completed torrents, so you don't need to keep the app open all day long.  When you touch the notification it opens the app.

is this what you need?

Best regards!

**Comment by Fale** [comment]
Thanks :)
