### ISSUE TITLE
Feature: Easier access to priority controls

### ISSUE THREAD

**Issue by eeque** [lgallard/qBittorrent-Client#7]
Hey,

Love the app. However, there is one small thing I feel the need to point out. On my phone, if you want to change the queue order (priority) of a torrent, it involves clicking on the name of a torrent, going to the overflow menu and then finding the Increase/Decrease priority button. You're then brought to the torrent list screen by the app and have to repeat the process.
Thing is, this becomes a hassle if you're running any borderline substantial number of torrents (imagine doing this ~15 times).

You obviously have UI concerns; so may I recommend the addition of "Move to Top / Bottom" buttons somewhere? That'll save you from adding Increase / Decrease priority buttons on the list screen (which IMHO, is more correct). 

Other small things (I can create separate issues for these if you wish):
1. Shutdown qBittorrent from the app. qB is a desktop client so assuming I need the bandwidth for something else inside the house, I don't have to go through SSH / Web interface shenanigans.
2. That "Refreshing" message. Are you sure that's absolutely necessary? 
3. Possibly an option to further reduce the Refresh Interval from 30s.

Thanks. :)

**Comment by lgallard** [comment]
By the way, another option of handling the bandwidth is the "Pause all" option...and use the "Resume all" option to resume your torrents whenever you want.

Also remember you can manage bandwidth qBittorrent uses from "Options". 

Best regards!

**Comment by eeque** [comment]
Sorry about the delay. Life got in the way. You're right about the "Pause all" option. In fact, it occurred to me as soon as I posted the original entry. In fact, you're so right that I think a Shutdown option is purely cosmetic now, because if I want to restart a download, I'd have to resort to the same SSH shenanigans as before.

I've added 2 more issues. I hope this one is fine as a way to track the issue in the title.

Just an aside, and the decision is purely yours, wouldn't it make slightly more sense to stay on the Torrent Details screen after clicking on something in the overflow menu?

**Comment by lgallard** [comment]
eeque so now you think the shutdown option in not necessary?

Regarding the staying on the Torrent Details screen after clicking on something in the overflow menu, I thought people would like to see the change in the torrent lists after performing the action.

I can change this behaviour, but it will be in future releases because I have to change how the application interacts in the phone and tablet versions.

Best regards!

**Comment by lgallard** [comment]
* Added top and bottom priority options …
* Added increase and decrease priority in multi choice mode

These option will be available in the next release!
