### ISSUE TITLE
Feature: Reduce refresh interval

### ISSUE THREAD

**Issue by eeque** [lgallard/qBittorrent-Client#8]
The reduce interval should have an option to be lower than 30s. Given the increments already present, how about something like an option for 2 / 5 seconds?

Related: The "refreshing" message should have an option to be disabled unless the manual refresh button is clicked on. This makes sense because if:
a) The refresh interval is small, it'll just be present on the screen all the time.
b) The refresh interval is large, it serves very little purpose because the implication is that someone is just staring at their phone / tablet screen waiting to get that little bit of data. Anyone who uses a large refresh interval will most likely end up using the manual refresh button when they fire up the app as it is.

**Comment by lgallard** [comment]
eeque the refresh options will be included in release 3.4.x.

Regarding the "Refreshing" message, it will be deleted in release 3.3.0 in few days, because you are right, it doesn't make sense having that message if there is a progress bar that indicates an action is being performed.

Best regards!

**Comment by lgallard** [comment]
Added refreshing options:

* 5 seconds
* 10 seconds
* 15 seconds
* 20 seconds

They will be included in the next release.
