### ISSUE TITLE
Feature: Torrent completion notification

### ISSUE THREAD

**Issue by eeque** [lgallard/qBittorrent-Client#9]
Like the name suggests. An option for a notification upon completion of a torrent would add to the "completeness" of the app. I say "option" because someone is going to go nuts when their screen on time goes from 5 hours to 4:55.

**Comment by lgallard** [comment]
eeque I already thought about it, but I have to decide if I implement that feature in a service or if the app should check for completed torrents. Also I have to think a way to keep the track of each torrent, so you don't get repeated notifications.

Therefore I will be include in future releases.

Best regards

**Comment by lgallard** [comment]
Added in the pro version

**Comment by lgallard** [comment]
Added to the free version!
